apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
  name: projectdec21
contexts:
- context:
    cluster: projectdec21
    namespace: 
    user: root-user
  name: 
users:
- name: 
----------------------------------------

current-context: federal-context
apiVersion: v1
kind: Config
clusters:
- cluster: projectdec21
    api-version: v1
    server: http://xyz:8080
  name: 
  
- context:
    cluster: projectdec21
    namespace: 
    user: 
  name: 
preferences:
  colors: true
users:
- name: 
  user:
    token: 
- name: 
  user:
    client-certificate: path/to/my/client/cert
    client-key: path/to/my/client/key
